services:

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "7777:7777"
    volumes:
      - ./develop/datasets/clean:/app/dataset

  ml-api:
    build: ./ml-api
    ports:
      - "5000:5000"
    volumes:
      - ./develop/datasets/clean:/app/dataset